# Generated by Django 5.1.4 on 2024-12-12 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('edad', models.PositiveSmallIntegerField()),
                ('nombre', models.CharField(max_length=10)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=25, unique=True)),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajadore',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('edad', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=25, unique=True)),
                ('specialty', models.CharField(choices=[('Medicina Interna', 'Médico Internista'), ('Cardiología', 'Cardiólogo'), ('Neumología', 'Neumólogo'), ('Endocrinología', 'Endocrinólogo'), ('Gastroenterología', 'Gastroenterólogo'), ('Hematología', 'Hematólogo'), ('Inmunología', 'Inmunólogo'), ('Reumatología', 'Reumatólogo'), ('Nefrología', 'Nefrólogo'), ('Oncología', 'Oncólogo'), ('Pediatría', 'Pediatra'), ('Psiquiatría', 'Psiquiatra'), ('Dermatología', 'Dermatólogo'), ('Neurología', 'Neurólogo')], default='Ninguno', max_length=20)),
                ('afiliacion', models.CharField(choices=[('Fonasa', 'fonasa'), ('Isapre', 'isapre'), ('Ambos', 'ambos')], default='Ninguno', max_length=20)),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default='Ninguno', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HorarioDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miercoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes')], default='Ninguno', max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('is_valid', models.BooleanField(default=True)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.trabajadore')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmada', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
                ('dia', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='api.horariodisponible')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.trabajadore')),
            ],
        ),
    ]
